In [19]:
from array import *

import pandas as pd
df = pd.read_csv('data/imitation+privacy-policy.csv', header=None)
print(df)
# print(df.loc[[0]][1])

    0   1   2   3   4   5   6   7   8   9  ...  22  23  24  25  26  27  28  \
0    4   2   4   2   2   1   3   2   1   2 ...   1   2   4   2   4   1   3   
1    4   1   3   1   3   1   1   2   3   2 ...   2   2   4   1   4   1   1   
2    4   2   4   2   1   2   3   1   3   1 ...   3   2   4   2   4   1   1   
3    4   1   4   2   1   2   1   1   1   2 ...   1   2   1   2   3   2   1   
4    4   2   4   2   2   2   3   1   1   2 ...   1   2   4   2   4   1   1   
5    4   1   4   1   1   2   3   1   1   2 ...   1   2   3   1   4   2   2   
6    2   1   1   1   1   2   1   2   3   1 ...   1   1   1   2   3   1   1   
7    1   2   1   1   1   2   1   1   1   1 ...   3   1   2   1   2   1   1   
8    4   2   4   2   1   2   3   2   1   2 ...   3   2   1   2   3   2   1   
9    4   2   4   1   1   2   3   1   1   2 ...   4   2   4   2   4   2   1   
10   4   1   4   2   2   2   3   2   4   1 ...   1   2   3   1   4   2   3   
11   4   2   3   1   3   2   2   1   1   2 ...   1   2   1   1  

In [20]:
import numpy as np
df_adj = pd.read_csv('data/adjacency.csv', header=None, index_col=False)
#df_adj = pd.DataFrame(np.loadtxt('data/adjacency.csv', dtype=int))
#df_adj

In [38]:
import random

agentlocations = []
agentpolicies = []

initlocation = []
initpolicy = []

column_names = ['step', 'id', 'context', 'policy']
df_context_policies  = pd.DataFrame(columns = column_names)
df_context_policies

for a in range(0,24):
    #print(a)
    context = random.randint(1,16)
    #initlocation.insert(a, location)
    #print(int(df.loc[[a]][initlocation[a]*2-2]))
    policy = int(df.loc[[a]][location*2-2])
    #initpolicy.insert(a, int(df.loc[[a]][location*2-2]))
    #currentlocations.append(location)
    #currentpolicies.append(int(df.loc[[a]][location*2-2]))
    
    df_context_policies.loc[len(df_context_policies)] = [0, a, context, policy]
    
#print(initlocation)    
#print(initpolicy)    

#agentlocations.append(initlocation)
#agentpolicies.append(initpolicy)



for t in range(1,100):
    #currentlocations = agentlocations[t-1]
    #currentpolicies = agentpolicies[t-1]
    for a in range(0,24):
        moveprob = random.randint(1,100)
        if moveprob < 25:
            context = random.randint(1,16)
            policy = int(df.loc[[a]][location*2-2])
        else:
            index = a + (t-1)*24
            context = df_context_policies.loc[index]['context']
            #context = df_context_policies.loc[(df_context_policies['step'] == t-1) & (df_context_policies['id'] == a)]['context']
            policy = df_context_policies.loc[index]['policy']
            #policy = df_context_policies.loc[(df_context_policies['step'] == t-1) & (df_context_policies['id'] == a)]['policy']

        df_context_policies.loc[len(df_context_policies)] = [t, a, context, policy]
            
        #currentsharingpolicies[]

    #print("\n Current:", currentlocations)
    #agentlocations.append(currentlocations)
    #print("\n All: ", agentlocations)
    
    #agentpolicies.append(currentpolicies)

# #print("Locations", agentlocations)
# #print("Policies", agentpolicies)



# df_locations=pd.DataFrame(data=agentlocations)
# #print("\n\n", agentlocations)
# #print(df_locations)

df_context_policies

step  id context policy
0       0   0       9      3
1       0   1      11      1
2       0   2      11      1
3       0   3       9      1
4       0   4       2      1
5       0   5      14      2
6       0   6       1      1
7       0   7       1      1
8       0   8      14      1
9       0   9      15      1
10      0  10       8      3
11      0  11      11      1
12      0  12      11      1
13      0  13       3      1
14      0  14       6      1
15      0  15      15      1
16      0  16      14      1
17      0  17      12      1
18      0  18       9      1
19      0  19      16      3
20      0  20       8      3
21      0  21      11      1
22      0  22       1      4
23      0  23       9      1
24      1   0       9      3
25      1   1      11      1
26      1   2      11      1
27      1   3       9      1
28      1   4       2      1
29      1   5       3      2
...   ...  ..     ...    ...
2370   98  18       8      1
2371   98  19       7      3
2372   98  20       6      3
2373   98  21       9      1
2374   98  22       5      4
2375   98  23       5      1
2376   99   0       4      3
2377   99   1       1      1
2378   99   2       3      1
2379   99   3      15      1
2380   99   4       9      1
2381   99   5       2      2
2382   99   6      15      1
2383   99   7      12      1
2384   99   8       4      1
2385   99   9       1      1
2386   99  10      15      3
2387   99  11       2      1
2388   99  12      16      1
2389   99  13      13      1
2390   99  14       9      1
2391   99  15       3      1
2392   99  16      10      1
2393   99  17       9      1
2394   99  18      16      1
2395   99  19       7      3
2396   99  20       6      3
2397   99  21       9      1
2398   99  22       5      4
2399   99  23       5      1

[2400 rows x 4 columns]

In [58]:
import matplotlib.pyplot as plt  
#df_context_policies.shape
#df_context_policies.head

#X = df_context_policies.drop(['policy', 'step', 'id'], axis=1)  
X = df_context_policies.drop(['policy', 'step'], axis=1)  
y = df_context_policies['policy']

print(X)
print(y)

      id context
0      0       9
1      1      11
2      2      11
3      3       9
4      4       2
5      5      14
6      6       1
7      7       1
8      8      14
9      9      15
10    10       8
11    11      11
12    12      11
13    13       3
14    14       6
15    15      15
16    16      14
17    17      12
18    18       9
19    19      16
20    20       8
21    21      11
22    22       1
23    23       9
24     0       9
25     1      11
26     2      11
27     3       9
28     4       2
29     5       3
...   ..     ...
2370  18       8
2371  19       7
2372  20       6
2373  21       9
2374  22       5
2375  23       5
2376   0       4
2377   1       1
2378   2       3
2379   3      15
2380   4       9
2381   5       2
2382   6      15
2383   7      12
2384   8       4
2385   9       1
2386  10      15
2387  11       2
2388  12      16
2389  13      13
2390  14       9
2391  15       3
2392  16      10
2393  17       9
2394  18      16
2395  19       7
2396  20      

In [59]:
from sklearn.model_selection import train_test_split  
y=y.astype('int')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) 


print(X_train, y_train)

      id context
695   23       2
1334  14      11
422   14       3
1174  22       5
685   13       3
198    6      15
257   17       7
1479  15       9
141   21       2
488    8       1
1693  13       2
1996   4       2
977   17       1
1599  15       7
1939  19      15
1214  14       4
2384   8       4
1489   1       7
1340  20       8
1534  22      11
2172  12      11
2163   3      15
1086   6      11
2119   7       7
1979  11       8
63    15       1
1943  23      12
1824   0       3
6      6       1
805   13       7
...   ..     ...
149    5      12
642   18       6
1850   2      10
762   18       4
1312  16       9
1975   7      14
1830   6      15
1213  13       5
1844  20       3
1175  23       5
2035  19      10
1123  19       6
385    1       7
1559  23      14
1206   6       7
698    2      14
1950   6      15
421   13      11
880   16       4
1136   8      12
941    5      13
1204   4       7
1624  16       7
40    16       6
666   18       1
1172  20       8
1286  14      

In [60]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  

y_pred = svclassifier.predict(X_test)  


from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[364   0   0   0]
 [ 15   0   0   0]
 [ 84   0   0   0]
 [ 17   0   0   0]]
             precision    recall  f1-score   support

          1       0.76      1.00      0.86       364
          2       0.00      0.00      0.00        15
          3       0.00      0.00      0.00        84
          4       0.00      0.00      0.00        17

avg / total       0.58      0.76      0.65       480



/home/najmeri/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [70]:
d = {'id': [23, 22], 'context': [4, 7]}
df = pd.DataFrame(data=d)
svclassifier.predict(df)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,