In [1]:
from array import *

import pandas as pd
df = pd.read_csv('data/imitation+privacy-policy.csv', header=None)
print(df)
# print(df.loc[[0]][1])

    0   1   2   3   4   5   6   7   8   9  ...  22  23  24  25  26  27  28  \
0    4   2   4   2   2   1   3   2   1   2 ...   1   2   4   2   4   1   3   
1    4   1   3   1   3   1   1   2   3   2 ...   2   2   4   1   4   1   1   
2    4   2   4   2   1   2   3   1   3   1 ...   3   2   4   2   4   1   1   
3    4   1   4   2   1   2   1   1   1   2 ...   1   2   1   2   3   2   1   
4    4   2   4   2   2   2   3   1   1   2 ...   1   2   4   2   4   1   1   
5    4   1   4   1   1   2   3   1   1   2 ...   1   2   3   1   4   2   2   
6    2   1   1   1   1   2   1   2   3   1 ...   1   1   1   2   3   1   1   
7    1   2   1   1   1   2   1   1   1   1 ...   3   1   2   1   2   1   1   
8    4   2   4   2   1   2   3   2   1   2 ...   3   2   1   2   3   2   1   
9    4   2   4   1   1   2   3   1   1   2 ...   4   2   4   2   4   2   1   
10   4   1   4   2   2   2   3   2   4   1 ...   1   2   3   1   4   2   3   
11   4   2   3   1   3   2   2   1   1   2 ...   1   2   1   1  

In [2]:
import numpy as np
df_adj = pd.read_csv('data/adjacency.csv', header=None, index_col=False)
#df_adj = pd.DataFrame(np.loadtxt('data/adjacency.csv', dtype=int))
#df_adj

In [5]:
import random

agentlocations = []
agentpolicies = []

initlocation = []
initpolicy = []

column_names = ['step', 'id', 'context', 'policy']
df_context_policies  = pd.DataFrame(columns = column_names)
df_context_policies

for a in range(0,24):
    #print(a)
    context = random.randint(1,16)
    #initlocation.insert(a, location)
    #print(int(df.loc[[a]][initlocation[a]*2-2]))
    policy = int(df.loc[[a]][context*2-2])
    #initpolicy.insert(a, int(df.loc[[a]][location*2-2]))
    #currentlocations.append(location)
    #currentpolicies.append(int(df.loc[[a]][location*2-2]))
    
    df_context_policies.loc[len(df_context_policies)] = [0, a, context, policy]
    
#print(initlocation)    
#print(initpolicy)    

#agentlocations.append(initlocation)
#agentpolicies.append(initpolicy)



for t in range(1,100):
    #currentlocations = agentlocations[t-1]
    #currentpolicies = agentpolicies[t-1]
    for a in range(0,24):
        moveprob = random.randint(1,100)
        if moveprob < 25:
            context = random.randint(1,16)
            policy = int(df.loc[[a]][context*2-2])
        else:
            index = a + (t-1)*24
            context = df_context_policies.loc[index]['context']
            #context = df_context_policies.loc[(df_context_policies['step'] == t-1) & (df_context_policies['id'] == a)]['context']
            policy = df_context_policies.loc[index]['policy']
            #policy = df_context_policies.loc[(df_context_policies['step'] == t-1) & (df_context_policies['id'] == a)]['policy']

        df_context_policies.loc[len(df_context_policies)] = [t, a, context, policy]
            
        #currentsharingpolicies[]

    #print("\n Current:", currentlocations)
    #agentlocations.append(currentlocations)
    #print("\n All: ", agentlocations)
    
    #agentpolicies.append(currentpolicies)

# #print("Locations", agentlocations)
# #print("Policies", agentpolicies)



# df_locations=pd.DataFrame(data=agentlocations)
# #print("\n\n", agentlocations)
# #print(df_locations)

df_context_policies

step  id context policy
0       0   0       5      1
1       0   1      11      1
2       0   2       2      4
3       0   3      13      1
4       0   4      16      1
5       0   5      11      1
6       0   6      16      1
7       0   7       8      2
8       0   8       4      3
9       0   9      13      4
10      0  10      11      3
11      0  11       7      3
12      0  12       9      3
13      0  13      13      1
14      0  14      13      1
15      0  15      12      1
16      0  16      13      3
17      0  17       6      4
18      0  18       7      2
19      0  19       1      4
20      0  20       1      3
21      0  21       2      3
22      0  22       9      4
23      0  23       4      1
24      1   0       5      1
25      1   1      11      1
26      1   2       2      4
27      1   3      13      1
28      1   4      16      1
29      1   5      11      1
...   ...  ..     ...    ...
2370   98  18       8      1
2371   98  19      16      1
2372   98  20       8      1
2373   98  21       8      2
2374   98  22      15      4
2375   98  23      12      1
2376   99   0      11      1
2377   99   1       3      3
2378   99   2      14      4
2379   99   3      15      1
2380   99   4       4      3
2381   99   5       1      4
2382   99   6       9      3
2383   99   7       7      2
2384   99   8      10      1
2385   99   9       1      4
2386   99  10      10      1
2387   99  11       7      3
2388   99  12       2      4
2389   99  13      11      1
2390   99  14       9      4
2391   99  15       6      4
2392   99  16      13      3
2393   99  17       4      3
2394   99  18       8      1
2395   99  19      16      1
2396   99  20       8      1
2397   99  21       8      2
2398   99  22       8      1
2399   99  23      12      1

[2400 rows x 4 columns]

In [6]:
import matplotlib.pyplot as plt  
#df_context_policies.shape
#df_context_policies.head

#X = df_context_policies.drop(['policy', 'step', 'id'], axis=1)  
X = df_context_policies.drop(['policy', 'step'], axis=1)  
y = df_context_policies['policy']

print(X)
print(y)

      id context
0      0       5
1      1      11
2      2       2
3      3      13
4      4      16
5      5      11
6      6      16
7      7       8
8      8       4
9      9      13
10    10      11
11    11       7
12    12       9
13    13      13
14    14      13
15    15      12
16    16      13
17    17       6
18    18       7
19    19       1
20    20       1
21    21       2
22    22       9
23    23       4
24     0       5
25     1      11
26     2       2
27     3      13
28     4      16
29     5      11
...   ..     ...
2370  18       8
2371  19      16
2372  20       8
2373  21       8
2374  22      15
2375  23      12
2376   0      11
2377   1       3
2378   2      14
2379   3      15
2380   4       4
2381   5       1
2382   6       9
2383   7       7
2384   8      10
2385   9       1
2386  10      10
2387  11       7
2388  12       2
2389  13      11
2390  14       9
2391  15       6
2392  16      13
2393  17       4
2394  18       8
2395  19      16
2396  20      

In [7]:
from sklearn.model_selection import train_test_split  
y=y.astype('int')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) 


print(X_train, y_train)

      id context
258   18       3
1584   0       4
1387  19      12
1831   7      15
733   13       6
1491   3      16
1582  22      12
1832   8      12
628    4      11
278   14       7
1661   5       2
896    8       9
1979  11       1
1440   0      12
1701  21      11
1873   1      16
1033   1      11
1759   7      16
728    8       2
688   16       3
1326   6      13
2167   7       3
1659   3       7
929   17       1
2315  11       7
1966  22       2
874   10       7
867    3       2
2326  22      15
1807   7      15
...   ..     ...
1147  19      11
1713   9      12
1617   9       9
2276  20       7
123    3      16
1838  14       9
1848   0      13
1305   9      15
125    5      10
261   21       4
1653  21      15
449   17       9
696    0       6
2304   0      12
964    4       5
1198  22       8
539   11      15
709   13       6
1652  20      16
471   15       7
172    4      16
238   22       3
1516   4       1
875   11       6
2211   3      14
832   16       3
2017   1      

In [8]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  

y_pred = svclassifier.predict(X_test)  


from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[157   0   0  46]
 [ 47   0   0  11]
 [ 62   0   0  51]
 [ 33   0   0  73]]
             precision    recall  f1-score   support

          1       0.53      0.77      0.63       203
          2       0.00      0.00      0.00        58
          3       0.00      0.00      0.00       113
          4       0.40      0.69      0.51       106

avg / total       0.31      0.48      0.38       480



/home/najmeri/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
d = {'id': [23, 22], 'context': [4, 7]}
df = pd.DataFrame(data=d)
svclassifier.predict(df)

array([1, 1])